# 开发环境配置

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fullstack_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  redis:
    host: localhost
    port: 6379

# 日志配置
logging:
  level:
    com.example.api: debug
    org.springframework.web: info

# 自定义配置
application:
  security:
    allowed-origins: http://localhost:3000,http://localhost:8080
  stripe:
    api-key: sk_test_your-key
    webhook-secret: whsec_your-webhook-secret