# 生产环境配置

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:fullstack_db}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

# 日志配置
logging:
  level:
    com.example.api: info
    org.springframework.web: warn

# 自定义配置
application:
  security:
    allowed-origins: ${ALLOWED_ORIGINS:https://your-domain.com,https://admin.your-domain.com}
  stripe:
    api-key: ${STRIPE_API_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}