server:
  port: 9090
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  application:
    name: spring-boot-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fullstack_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10s
  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.api.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true

# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false

# 自定义配置
application:
  security:
    allowed-origins: http://localhost:3000,http://localhost:8080
  stripe:
    api-key: sk_test_your-key
    webhook-secret: whsec_your-webhook-secret
  file:
    upload-dir: ./uploads
    allowed-file-types: jpg,jpeg,png,pdf,docx,xlsx